openapi: 3.0.0
info:
  title: yfid-expressjs
  version: 0.1.0
servers:
  - url: http://{{base_url}}
tags:
  - name: home
paths:
  /:
    get:
      tags:
        - home
      summary: index
      responses:
        '200':
          description: OK
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Content-Type:
              schema:
                type: string
                example: application/vnd.api+json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '21'
            ETag:
              schema:
                type: string
                example: W/"15-fWwxo68NlPRHzd7O4auWM6L7XY4"
            Set-Cookie:
              schema:
                type: string
                example: >-
                  connect.sid=s%3AxlI73y8JKFsYd6OnWT4XamEwdnLe1q4x.cejD86VfUFkXo33FL%2F%2BDBbDwjWiX0CIseTOhSk4DL1o;
                  Path=/; Expires=Thu, 01 Feb 2024 01:36:23 GMT; HttpOnly
            Date:
              schema:
                type: string
                example: Thu, 01 Feb 2024 01:35:23 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              example:
                message: Express
  /app-version:
    get:
      tags:
        - home
      summary: app-version
      responses:
        '200':
          description: OK
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Content-Type:
              schema:
                type: string
                example: application/vnd.api+json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '23'
            ETag:
              schema:
                type: string
                example: W/"17-nHkSQ6mrMk3Hv7nuQX+wjFYT0mA"
            Date:
              schema:
                type: string
                example: Thu, 01 Feb 2024 01:35:51 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              example:
                app-version: 0.1.0
